### ISSUE TITLE
카테고리 기능 구현

### ISSUE THREAD

**Issue by icarus012832** [SSGSAKK/ssgsakk-be#3]
### Description
카테고리에 관련된 기능들이 필요합니다.

### Tasks
- [x] 카테고리 테이블 생성
- [ ] 카테고리 조회 기능 구현
- [ ] 카테고리 삭제 기능 구현

**Comment by hoontaepark** [comment]
빠르게 만들겠습니다 죄송합니다
